spring:
  application:
    name: coffee-pos
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_pos?useUnicode=true
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baselineOnMigrate: true

logging:
  level:
    root: INFO
    com.coffee.pos: DEBUG
  file:
    name: logs/application.log
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_SECRET:86400}