spring:
  application:
    name: coffee-pos
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_pos?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baselineOnMigrate: true

logging:
  level:
    root: INFO
    com.coffee.pos: DEBUG
  file:
    name: logs/application.log
jwt:
  secret: 48e48065b44c4d117dc08c49567bf4d9
  expiration: 86400