spring:
  application:
    name: coffee-pos
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_pos?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baselineOnMigrate: true